### ISSUE TITLE
The following implimentation is taking even more time than the sequential one

### ISSUE THREAD

**Issue by RyanBrown835** [Padraig20/Global-Pair-Wise-Sequence-Alignment#1]
Hello i tried to run your code but its taking even more time than the sequential implementation 

```
//wavefront algorithm
#pragma omp parallel
{
      #pragma omp single
      {
          int waves = rows + cols - 1;
          for (int wave = 0; wave < waves; wave++) {
          #pragma omp taskloop grainsize(grainsize)
              for (int i = 1; i < rows; i++) {
                  int j = wave - i;
                  if (j >= 1 && j < cols) {
				float match = S[i - 1][j - 1] + SUB[ cmap.at(X[i - 1]) ][ cmap.at(Y[j-1]) ];
				float del = S[i - 1][j] + gap_penalty;
				float insert = S[i][j - 1] + gap_penalty;
				S[i][j] = std::max({match, del, insert});
				#pragma omp atomic update
                      thread_counters[omp_get_thread_num()]++;
                  }
              }
          }
      }
}

```

Here are the results

> == Sequential version completed in 11.9526 seconds. Entries visited: 2761492321 Score: 18639, Similarity Score: 40146, Identity Score: 40146, Gaps: 6062, Length (with gaps): 55591

> == Parallel version completed in 30.5004 seconds. Entries visited: 2761492321 Score: 18639, Similarity Score: 40146, Identity Score: mismatch -1, gap_penalty: -2 Matrix S size: [51481x53641]

**Comment by Padraig20** [comment]
Hi, thanks for telling me! Check again, forgot pushing the newest version...

![image](https://github.com/user-attachments/assets/9ffc43aa-29b2-40b2-b331-46d767bca218)

**Comment by RyanBrown835** [comment]
Thanks for the update but unfortunately i dont see any changes in implementation.hpp
the only change i see is in main file 
<img width="946" alt="Screenshot 2024-10-31 at 2 12 22 PM" src="https://github.com/user-attachments/assets/48a1660b-53d1-45b2-92a3-2fce8eb9d066">

**Comment by Padraig20** [comment]
Oh, I just saw... well I'm sorry, but I fear I there is no problem in the implementation. But there is in fact an overhead if you don't run the parallel version with enough threads. This is a common property in parallel algorithms. Are you using enough threads?

**Comment by RyanBrown835** [comment]
Yes, I am running with 32 threads, and idk why it's taking more time in parallel

```
[root]$ OMP_NUM_THREADS=32 srun --nodes=1 ./gpsa --exec-mode 1 --grain-size 256 --x X2.txt --y Y2.txt 
Loaded X and Y sequences with sizes 32767 and 32767
Scoring scheme: match: 1, mismatch -1, gap_penalty: -2
Matrix S size: [32768x32768]
== Sequential version completed in 4.64262 seconds.
   Entries visited: 1073741824 
   Score: 4246, Similarity Score: 21433, Identity Score: 21433, Gaps: 3902, Length (with gaps): 34718


[root]$ OMP_NUM_THREADS=32 srun --nodes=1 ./gpsa --exec-mode 2 --grain-size 256 --x
 X2.txt --y Y2.txt 
Loaded X and Y sequences with sizes 32767 and 32767
Scoring scheme: match: 1, mismatch -1, gap_penalty: -2
Matrix S size: [32768x32768]
Workload partitioning: 52360740 45517998 44554581 40959014 40004401 40147546 24038835 26368043 38120790 33723504 27083478 23134537 26941372 22597338 23891136 30725997 22470504 26909586 22380100 22570189 21606292 35901395 25444366 24898450 22860308 31878766 38709182 44900737 42573412 44267479 37487089 68714659 

== Parallel version completed in 38.3955 seconds.
   Entries visited: 1073741824 
   Score: 4246, Similarity Score: 21433, Identity Score: 21433, Gaps: 3902, Length (with gaps): 34718
```

**Comment by Padraig20** [comment]
Sometimes there's also overhead when you use too many threads :) I got 16 threads, wanna try that?

**Comment by RyanBrown835** [comment]
Sorry for taking your time 
The image you attached is also confusing. Does its partitioning work in the sequential version?

![image](https://github.com/user-attachments/assets/83f83bf8-ca06-48ac-9012-b64b06fb2fb6)

**Comment by Padraig20** [comment]
It's just bad formatting! If you look into the code, I print this out in the parallel part!

**Comment by RyanBrown835** [comment]
Thank you idk whats going on its still slowing down for me when i use omp for it works but while using omp taskloop its not i will figure something out thank you

**Comment by RyanBrown835** [comment]
I figured out what's wrong 

You're implementation of algorithm is incorrect you are looping over a very huge matrix because you have added rows + cols

Even though the if condition skip other iteration it still going over those iteration
